# Generated by Django 5.2 on 2025-04-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_card_like_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="noutbooks",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.category",
            ),
            preserve_default=False,
        ),
    ]
